// Event Categories
export const GA_CATEGORIES = {
    ONBOARDING: 'onboarding',
    QUESTIONS: 'questions',
    LETTER: 'letter',
    FEEDBACK: 'feedback',
    ERROR: 'error',
    ENGAGEMENT: 'engagement'
  } as const;
  
  // Event Names
  export const GA_EVENTS = {
    // Takedown Letter Generator events
    TDLG_START_YOUR_REQUEST_CLICKED: 'TDLG_START_YOUR_REQUEST_CLICKED',
    TDLG_PROCESS_STARTED: 'TDLG_PROCESS_STARTED',
    TDLG_PLATFORM_SELECTED: 'TDLG_PLATFORM_SELECTED',
    TDLG_INITIAL_QUESTIONS_COMPLETED: 'TDLG_INITIAL_QUESTIONS_COMPLETED',
    TDLG_REPORTING_QUESTIONS_COMPLETED: 'TDLG_REPORTING_QUESTIONS_COMPLETED',
    TDLG_ADDITIONAL_QUESTIONS_COMPLETED: 'TDLG_ADDITIONAL_QUESTIONS_COMPLETED',
    TDLG_REPORTING_STATUS_SELECTED: 'TDLG_REPORTING_STATUS_SELECTED',
    TDLG_ADDITIONAL_QUESTIONS_GENERATED: 'TDLG_ADDITIONAL_QUESTIONS_GENERATED',
    TDLG_LETTER_GENERATED: 'TDLG_LETTER_GENERATED',
    TDLG_LETTER_REGENERATED: 'TDLG_LETTER_REGENERATED',
    TDLG_LETTER_COPIED: 'TDLG_LETTER_COPIED',
    TDLG_PROCESS_COMPLETED: 'TDLG_PROCESS_COMPLETED',
    TDLG_ERROR_OCCURRED: 'TDLG_ERROR_OCCURRED',
    TDLG_RETRY_ATTEMPTED: 'TDLG_RETRY_ATTEMPTED',
    TDLG_FEEDBACK_OPENED: 'TDLG_FEEDBACK_OPENED',
    TDLG_FEEDBACK_SUBMITTED: 'TDLG_FEEDBACK_SUBMITTED',
    TDLG_LETTER_FEEDBACK_SUBMITTED: 'TDLG_LETTER_FEEDBACK_SUBMITTED',
    TDLG_LETTER_FEEDBACK_CONSENT_TO_SHARE: 'TDLG_LETTER_FEEDBACK_CONSENT_TO_SHARE',

    TDLG_VOICE_INPUT_USED: 'TDLG_VOICE_INPUT_USED',
    
    // Continue button events
    TDLG_PLATFORM_CONTINUE_CLICKED: 'TDLG_PLATFORM_CONTINUE_CLICKED',
    TDLG_REMOVAL_PROCESS_CONTINUE_CLICKED: 'TDLG_REMOVAL_PROCESS_CONTINUE_CLICKED',
    TDLG_INITIAL_QUESTIONS_CONTINUE_CLICKED: 'TDLG_INITIAL_QUESTIONS_CONTINUE_CLICKED',
    TDLG_REPORTING_DETAILS_CONTINUE_CLICKED: 'TDLG_REPORTING_DETAILS_CONTINUE_CLICKED',
    TDLG_FOLLOW_UP_CONTINUE_CLICKED: 'TDLG_FOLLOW_UP_CONTINUE_CLICKED',
    TDLG_NO_QUESTIONS_CONTINUE_CLICKED: 'TDLG_NO_QUESTIONS_CONTINUE_CLICKED',
    
    // General engagement events
    EXTERNAL_LINK_CLICKED: 'EXTERNAL_LINK_CLICKED',
    TDLG_BLOOM_IBA_COURSE_LINK_CLICKED: 'TDLG_BLOOM_IBA_COURSE_LINK_CLICKED',
    SOCIAL_LINK_CLICKED: 'SOCIAL_LINK_CLICKED',
    
    // Cookie Consent events
    COOKIE_CONSENT_ACCEPTED: 'COOKIE_CONSENT_ACCEPTED',
    COOKIE_CONSENT_DECLINED: 'COOKIE_CONSENT_DECLINED',
    COOKIE_POLICY_VIEWED: 'COOKIE_POLICY_VIEWED',
    
    // Error events
    ERROR_OCCURRED: 'ERROR_OCCURRED',
    RETRY_ATTEMPTED: 'RETRY_ATTEMPTED',

  } as const;